# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guardrails.proto
# Protobuf Python Version: 4.25.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10guardrails.proto\x12\nguardrails\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n\tGuardrail\x12\'\n\x04name\x18\x01 \x01(\x0e\x32\x19.guardrails.GuardrailName\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\"\xa3\x01\n\nGuardrails\x12)\n\nguardrails\x18\x01 \x03(\x0b\x32\x15.guardrails.Guardrail\x12\x17\n\nupdated_by\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x33\n\nupdated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01\x88\x01\x01\x42\r\n\x0b_updated_byB\r\n\x0b_updated_at\"H\n\x1bGuardrails_UpdateGuardrails\x12)\n\nguardrails\x18\x01 \x03(\x0b\x32\x15.guardrails.Guardrail*\xf0\x01\n\rGuardrailName\x12\x1e\n\x1aGUARDRAIL_NAME_UNSPECIFIED\x10\x00\x12$\n GUARDRAIL_NAME_JAILBREAK_DEFENCE\x10\x01\x12(\n$GUARDRAIL_NAME_HALLUCINATION_CONTROL\x10\x02\x12\x1e\n\x1aGUARDRAIL_NAME_AI_IDENTITY\x10\x03\x12\'\n#GUARDRAIL_NAME_EMERGENCY_ESCALATION\x10\x04\x12&\n\"GUARDRAIL_NAME_TOOL_CALL_INTEGRITY\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'guardrails_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GUARDRAILNAME']._serialized_start=377
  _globals['_GUARDRAILNAME']._serialized_end=617
  _globals['_GUARDRAIL']._serialized_start=65
  _globals['_GUARDRAIL']._serialized_end=134
  _globals['_GUARDRAILS']._serialized_start=137
  _globals['_GUARDRAILS']._serialized_end=300
  _globals['_GUARDRAILS_UPDATEGUARDRAILS']._serialized_start=302
  _globals['_GUARDRAILS_UPDATEGUARDRAILS']._serialized_end=374
# @@protoc_insertion_point(module_scope)
