# Copyright PolyAI Limited
class KnowledgeBase:
    def __init__(self) -> None: ...
    @property
    def disabled_topics(self) -> list[str]: ...
    def disable_topics(self, topic_names: list[str]) -> None: ...
    def enable_topics(self, topic_names: list[str]) -> None: ...
    def enable_all_topics(self) -> None: ...
